[tool.poetry]
name = "nba-db"
version = "0.1.0"
description = "all the necessary code for the production and update of the Kaggle NBA Database"
authors = ["Wyatt Walsh <wyattowalsh@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^1.5.3"
kaggle = "^1.5.12"
lxml = "^4.9.2"
html5lib = "^1.1"
python-dotenv = "^0.21.1"
cython = "^0.29.33"
pydantic = "^1.10.4"
pandera = {extras = ["hypotheses", "io", "mypy", "strategies"], version = "^0.13.4"}
sqlalchemy = "^1.4.46"
nba-api = "^1.1.13"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^3.6.0"
ipython-sql = "^0.4.1"
jupyterlab-system-monitor = "^0.8.0"
isort = "^5.12.0"
black = "^23.1.0"
pylint = "^2.16.2"
autoflake = "^2.0.1"
pylama = {version = "^8.4.1", extras = ["all"]}
nbdime = "^3.1.1"
jupyterlab-git = "^0.41.0"
jupyter-contrib-nbextensions = "^0.7.0"
hypothesis = "^6.66.0"
pytest = "^7.2.1"
pytest-sugar = "^0.9.6"
pytest-emoji = "^0.2.0"
pytest-html = "^3.2.0"
pytest-icdiff = "^0.6"
pytest-instafail = "^0.4.2"
pytest-timeout = "^2.1.0"
pytest-benchmark = "^4.0.0"
pytest-cov = "^4.0.0"
pytest-xdist = {version = "^3.2.0", extras = ["psutil"]}
sphinx = "^5"
pydata-sphinx-theme = "^0.12.0"
sphinx-copybutton = "^0.5.1"
myst-parser = "^0.18.1"
sphinxcontrib-mermaid = "^0.8.1"
sphinx-git = "^11.0.0"
sphinx-markdown-builder = "^0.5.5"
sphinx-design = "^0.3.0"
sphinx-autobuild = "^2021.3.14"
sphinx-hoverxref = "^1.3.0"
sphinx-sitemap = "^2.5.0"
sphinx-togglebutton = "^0.3.2"
sphinx-favicon = "^0.2"
tabulate = "^0.9.0"
pipreqs = "^0.4.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
src_paths = ["nba_db", "tests"]

[tool.autoflake]
remove-all-unused-imports = true
remove-unused-variables = true
in-place = true
ignore-init-module-imports = true

[tool.pylama]
skip = "*/.tox/*,*/.env/*"
linters = "eradicate,mccabe,pycodestyle,pyflakes,pylint,isort,pydocstyle"

[tool.pytest.ini_options]
addopts = "-n auto --verbose --hypothesis-show-statistics --html=logs/report.html --self-contained-html --emoji --instafail  --cov=nba_db tests/ --cov-append --cov-report html:logs/cov_html"
testpaths = ["tests"]
console_output_style = "progress"
junit_logging = "all"
log_cli = "True"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_cli_format = "%(asctime)s - [%(levelname)s] - %(name)s - (%(filename)s).%(funcName)s(%(lineno)d) - %(message)s"
log_cli_level = "DEBUG"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_file = "logs/pytest-logs.txt"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
log_file_format = "%(asctime)s - [%(levelname)s] - %(name)s - (%(filename)s).%(funcName)s(%(lineno)d) - %(message)s"
log_file_level = "DEBUG"
log_format = "%(asctime)s - [%(levelname)s] - %(name)s - (%(filename)s).%(funcName)s(%(lineno)d) - %(message)s"
log_level = "DEBUG"
required_plugins = [
    "pytest-sugar",
    "pytest-html",
    "pytest-emoji",
    "pytest-icdiff",
    "pytest-instafail",
    "pytest-timeout",
    "pytest-benchmark",
    "pytest-cov",
]
timeout = 500